### PR TITLE
S3 setup

### PR DESCRIPTION
**Pull request by eddiegabriel4**
s3 bucket working. gpt image parsing almost fully functional depending on receipt, associated database insertions also working. endpoint to get all user receipt urls. 

## Summary by CodeRabbit

- **New Features**
  - Integrated new environment variables for Clerk, Supabase, AWS S3, and OpenAI services.
  - Implemented a GitHub Actions workflow for automated linting and testing of Python code.
  - Added a new task in Gitpod configuration for installing Python dependencies.
  - Introduced pre-commit hooks for YAML checks, end-of-file fixer, trailing whitespace, and code formatting with Black and Ruff.
  - Created a comprehensive README for the budget tracking app project proposal.
  - Established a new database table for receipts with fields for user association, image URLs, and JSON data.
  - Added example flows and test results for user purchase logging, updating, and deletion.

- **Enhancements**
  - Updated the Python FastAPI application to support receipt image uploads to AWS S3 and data extraction via OpenAI API.
  - Enhanced the purchases and transactions API with new fields and improved validation.
  - Enforced email uniqueness in user creation and update processes.
  - Provided peer review feedback for project improvements in v4_instructions.md.

- **Bug Fixes**
  - Fixed potential issues with email uniqueness in user management.
  - Addressed pagination and error handling in transactions retrieval and updates.

- **Documentation**
  - Updated various README and markdown files to reflect new features and project instructions.

- **Refactor**
  - Modified environment variable access syntax in the database configuration file.

- **Style**
  - Set the default Python formatter to Black in VSCode settings.

- **Chores**
  - Updated .gitignore and .vercelignore files to exclude specific directories and files.
  - Added new configurations and build artifacts for the Next.js frontend application.

- **Tests**
  - Included new manual test results for API endpoints.

Please note that this summary is non-exhaustive and focuses on the most impactful changes for end-users.

### CODE REVIEW

**Comment by Sebi2k** [comment]
looks good!

**Comment by arnenoori** [comment]
the code is good. but be careful committing your .env.local file. also consider more robust edge cases such as checking if an email already exists.

**Comment by eddiegabriel4** [comment]
yes definitely learned my lesson with .env.local. Should be removed in most up to date commit. I'm working on making the code more stable in regardsto edge cases and will be in my next commit. Thanks

**Comment by Bryan-Nguyen-2004** [comment]
LGTM

**Pull request merged**
